version: '3.8'
services:
  dashy:
    # To build from source, replace 'image: lissy93/dashy' with 'build: .'
    # build: .
    image: lissy93/dashy:2.1.1
    container_name: brainstormr-dashy
    hostname: brainstormr-dashy

    # Pass in your config file below, by specifying the path on your host machine
    volumes:
      - /mnt/appdata/brainstormr/hub/my-config.yml:/app/public/conf.yml
    ports:
      - 3503:80

    # Set any environmental variables
    environment:
      - NODE_ENV=production

    # Specify your user ID and group ID. You can find this by running `id -u` and `id -g`
      - UID=1003
      - GID=1004

    # Specify restart policy
    restart: unless-stopped

    # Configure healthchecks
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - brainstormr

networks:
  brainstormr:
    external: true