version: '2'

services:
  brainstormr-redis:
    container_name: brainstormr-redis
    hostname: brainstormr-redis
    image: redis:7.0.5
    ports:
      - 3507:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s        
    labels:
      - com.centurylinklabs.watchtower.enable=true
    restart: unless-stopped
    networks:
      - brainstormr

networks:
  brainstormr:
    driver: bridge
    external: true