#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Format code with Prettier.
npm run make-style:prettier

# Stage the code.
git add .

# Check if the code was formatted.
npm run check-style:prettier

# Generates/updates Markdown trees that act as a table of contents for folder structure.
npm run markdown-notes-tree

# Stage the code.
git add .