---
version: '3.4'
services:
  brainstormr-authentik:
    image: beryju/authentik:2022.10
    container_name: brainstormr-authentik
    hostname: brainstormr-authentik
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: brainstormr-redis
      AUTHENTIK_POSTGRESQL__HOST: brainstormr-authentik-postgres
      AUTHENTIK_POSTGRESQL__USER: postgres
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: ${POSTGRES_PASSWORD}
      AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
      AUTHENTIK_SECRET_KEY: "${AUTHENTIK_SECRET_KEY}"
      
    #  AUTHENTIK_AUTHENTIK__GEOIP: "/geoip/GeoLite2-City.mmdb"
    #  GEOIPUPDATE_ACCOUNT_ID: "${GEOIPUPDATE_ACCOUNT_ID}"
    #  GEOIPUPDATE_LICENSE_KEY: "${GEOIPUPDATE_LICENSE_KEY}"
    volumes:
      - /mnt/appdata/brainstormr/authentik/media:/media
      - /mnt/appdata/brainstormr/authentik/custom-templates:/templates
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3506:9000"
      - "3505:9443"
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
    - brainstormr


  brainstormr-authentik_worker:
    image: beryju/authentik:2022.10
    container_name: brainstormr-authentik_worker
    hostname: brainstormr-authentik_worker
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: brainstormr-redis
      AUTHENTIK_POSTGRESQL__HOST: brainstormr-authentik-postgres
      AUTHENTIK_POSTGRESQL__USER: postgres
      AUTHENTIK_POSTGRESQL__NAME: authentik
      AUTHENTIK_POSTGRESQL__PASSWORD: ${POSTGRES_PASSWORD}
      AUTHENTIK_ERROR_REPORTING__ENABLED: "true"
      AUTHENTIK_SECRET_KEY: "${AUTHENTIK_SECRET_KEY}"
    # This is optional, and can be removed. If you remove this, the following will happen
    # - The permissions for the /media folders aren't fixed, so make sure they are 1000:1000
    # - The docker socket can't be accessed anymore
    user: root
    volumes:
      - /mnt/appdata/brainstormr/authentik/media:/media
      - /mnt/appdata/brainstormr/authentik/certs:/certs
      - /mnt/appdata/brainstormr/authentik/custom-templates:/templates      
      - /var/run/docker.sock:/var/run/docker.sock

    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
    - brainstormr

  # geoipupdate:
  #   image: "maxmindinc/geoipupdate:v4.9"
  #   container_name: geoipupdate
  #   hostname: geoipupdate
  #   volumes:
  #     - "/mnt/appdata/geoip:/usr/share/GeoIP"
  #   environment:
  #     GEOIPUPDATE_ACCOUNT_ID: "${GEOIPUPDATE_ACCOUNT_ID}"
  #     GEOIPUPDATE_LICENSE_KEY: "${GEOIPUPDATE_LICENSE_KEY}"
  #     GEOIPUPDATE_EDITION_IDS: "GeoLite2-City"
  #     GEOIPUPDATE_FREQUENCY: "8"
  #     GEOIPUPDATE_HOST: "updates.maxmind.com"
  #   labels:
  #     - com.centurylinklabs.watchtower.enable=true
  #   networks:
  #     - brainstormr



  brainstormr-authentik-postgres:
    image: postgres:12-bullseye
    container_name: brainstormr-authentik-postgres
    hostname: brainstormr-authentik-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: authentik
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 3504:8080
    networks:
      - brainstormr
networks:
  brainstormr:
    driver: bridge
    external: true